services:
  postgres-sales:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sales
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    command: |
      postgres -c 'max_connections=2000'
    volumes:
      - "./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql"
    healthcheck:
      test: pg_isready -h 127.0.0.1 -U postgres -d sales
      interval: 5s

  postgres-customer-item:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: customer_item
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - "./db/customer_item.sql:/docker-entrypoint-initdb.d/customer_item.sql"
    healthcheck:
      test: pg_isready -h 127.0.0.1 -U postgres -d customer_item
      interval: 5s

  dbgate:
    image: dbgate/dbgate
    environment:
      CONNECTIONS: sales, master

      LABEL_master: postgres-sales
      SERVER_master: postgres-sales
      USER_master: postgres
      PASSWORD_master: postgres
      PORT_master: 5432
      ENGINE_master: postgres@dbgate-plugin-postgres

      LABEL_purchase: postgres-customer-item
      SERVER_purchase: postgres-customer-item
      USER_purchase: postgres
      PASSWORD_purchase: postgres
      PORT_purchase: 5432
      ENGINE_purchase: postgres@dbgate-plugin-postgres

  dummy-sales-log:
    image: ghcr.io/yo1000/dummy-sales-log:latest
    ports:
      - 8081:8080
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: broker:29092
      SPRING_KAFKA_TEMPLATE_DEFAULTTOPIC: sales-log
      APP_THREAD_NOISESPERSEC: 500
    depends_on:
      - broker

  kafka:
    image: apache/kafka-native
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1

  kafka-ui:
    image: provectuslabs/kafka-ui
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=docker-kafka-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    ports:
      - "18081:8080"
    depends_on:
      - kafka
