spring:
  application:
    name: kafka-consumer
  datasource:
    hikari:
      maximum-pool-size: 80
  kafka:
    template:
      default-topic: sales-log
    listener:
      concurrency: 5
    consumer:
      group-id: sales-log
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.example.kafka.consumer.domain.entity.SalesLog
